name: Test behind main
on:
  - workflow_dispatch
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check whether the branch is behind main
        uses: spencercjh/git-branch-behind-main@main